openapi: 3.0.0
x-stoplight:
  id: prclvl27vr58e
info:
  title: API-memo
  version: '1.0'
  description: API for managing memos
servers:
  - url: 'http://localhost:3000'
paths:
  /category:
    post:
      summary: Create New User
      operationId: postCategory
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
        '400':
          description: Missing Required Information
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCategoryRequest'
        description: Post the necessary fields for the API to create a new category.
      description: Create a new category.
      parameters: []
    parameters: []
  '/category/{id}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDataResponse'
        '500':
          description: Internal Server Error
      operationId: get-category-id
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-category-id
      responses:
        '200':
          description: Update Data Success
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCategoryData'
  /categories:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDataResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: GetMemos
      description: ''
    parameters: []
  /healthz:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                Example 1:
                  value:
                    status: alive
      operationId: GetHealthz
  /readiness:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    status: ready
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Example 1:
                  value:
                    status: not ready
      operationId: GetReadiness
components:
  schemas:
    CreateCategoryRequest:
      title: CreateCategory
      x-stoplight:
        id: 70c88bea565aa
      type: object
      x-examples:
        Example 1:
          categoryCode: 0
          categoryName: string
          categoryGroup: string
          categoryEmail: user@example.com
          created_at: '2019-08-24T14:15:22Z'
      properties:
        categoryCode:
          type: integer
          x-stoplight:
            id: rbq1uwfcb1wde
        categoryName:
          type: string
          x-stoplight:
            id: c2zrvkw3ssbeb
        categoryGroup:
          type: string
          x-stoplight:
            id: omxcxg2uiajrg
        categoryEmail:
          type: string
          x-stoplight:
            id: 1ljflpb1cnxuz
          format: email
        created_at:
          type: string
          description: The date that the user was created.
          x-stoplight:
            id: 5g06zi2662ofi
          format: date-time
      required:
        - categoryCode
        - categoryName
        - categoryGroup
        - categoryEmail
        - created_at
    PostResponse:
      title: PostResponse
      x-stoplight:
        id: 14kmteatt69mg
      type: object
      properties:
        id:
          type: string
        message:
          type: string
          x-stoplight:
            id: 4vimk80dd0dzp
    CategoryDataResponse:
      title: CategoryDataResponse
      x-stoplight:
        id: c63323d38hmwv
      type: object
      properties:
        id:
          type: integer
        categoryCode:
          type: integer
          x-stoplight:
            id: qo3r94azbegri
        categoryName:
          type: string
          x-stoplight:
            id: lwdgjpppffjqh
        categoryGroup:
          type: string
          x-stoplight:
            id: l6xlxenlyq3dc
        categoryEmail:
          type: string
          x-stoplight:
            id: fsq446eu8wjc1
          format: email
        created_at:
          type: string
          x-stoplight:
            id: mc44tyn0a2a06
          format: date-time
        updated_at:
          type: string
          x-stoplight:
            id: 2gdd7hgrazc5w
          format: date-time
        deleted_at:
          type: string
          x-stoplight:
            id: e7kdiddi3t2aq
          format: date-time
      x-examples:
        Example 1:
          id: 0
          categoryCode: 0
          categoryName: string
          categoryGroup: string
          categoryEmail: user@example.com
          created_at: '2019-08-24T14:15:22Z'
          updated_at: '2019-08-24T14:15:22Z'
          deleted_at: '2019-08-24T14:15:22Z'
    UpdateCategoryData:
      title: UpdateCategoryData
      x-stoplight:
        id: 3yzolyjn1hwwo
      type: object
      properties:
        id:
          type: string
        categoryCode:
          type: string
          x-stoplight:
            id: 85ebxlfp4zf6j
        categoryName:
          type: string
          x-stoplight:
            id: 9ldh8rse2ptxj
        categoryGroup:
          type: string
          x-stoplight:
            id: 37uqe1an4ng07
        categoryEmail:
          type: string
          x-stoplight:
            id: lc96kt57x5j83
        created_at:
          type: string
          x-stoplight:
            id: mm5a1c9w8morc
        updated_at:
          type: string
          x-stoplight:
            id: a4r3oxx3d6xmy
        deleted_at:
          type: string
          x-stoplight:
            id: oobex15ut7ne9
      x-examples:
        Example 1:
          id: string
          categoryCode: string
          categoryName: string
          categoryGroup: string
          categoryEmail: string
          created_at: string
          updated_at: string
          deleted_at: string
